export const AUTH_USER_REQUEST = 'AUTH_USER_REQUEST'
export const AUTH_USER_ERROR = 'AUTH_USER_ERROR'
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS'

export const ADD_NEW_TEST_REQUEST = 'ADD_NEW_TEST_REQUEST'
export const ADD_NEW_TEST_ERROR = 'ADD_NEW_TEST_ERROR'
export const ADD_NEW_TEST_SUCCESS = 'ADD_NEW_TEST_SUCCESS'


export const GET_ALL_TESTS_REQUEST = 'GET_ALL_TESTS_REQUEST'
export const GET_ALL_TESTS_SUCCESS = 'GET_ALL_TESTS_SUCCESS'
export const GET_ALL_TESTS_ERROR = 'GET_ALL_TESTS_ERROR'


export const GET_ALL_ANSWERS_REQUEST = 'GET_ALL_ANSWERS_REQUEST'
export const GET_ALL_ANSWERS_SUCCESS = 'GET_ALL_ANSWERS_SUCCESS'
export const GET_ALL_ANSWERS_ERROR = 'GET_ALL_ANSWERS_ERROR'


export const GET_QUESTIONS_BY_LEVEL_REQUEST = 'GET_QUESTIONS_BY_LEVEL_REQUEST'
export const GET_QUESTIONS_BY_LEVEL_SUCCESS = 'GET_QUESTIONS_BY_LEVEL_SUCCESS'
export const GET_QUESTIONS_BY_LEVEL_ERROR = 'GET_QUESTIONS_BY_LEVEL_ERROR'


export const SUBMIT_DONE_TEST_REQUEST = 'SUBMIT_DONE_TEST_REQUEST'
export const SUBMIT_DONE_TEST_SUCCESS = 'SUBMIT_DONE_TEST_SUCCESS'
export const SUBMIT_DONE_TEST_ERROR = 'SUBMIT_DONE_TEST_ERROR'

export const SET_QUESTION_WITH_ANSWER = 'SET_QUESTION_WITH_ANSWER'
